# Generated by Django 4.1.7 on 2023-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0006_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPL_Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
    ]
